export const strings = {
  SignIn: 'Đăng nhập',
  SignUp: 'Đăng kí tài khoản',
  ContinueFacebook: 'Tiếp tục bằng Facebook',
  ContinueGoogle: 'Tiếp tục bằng Google',
  SignUpEmail: 'Đăng kí bằng email',
  MemberAlready: 'Đã đăng kí bằng email?',
  Email: 'Email của bạn',
  Password: 'Mật khẩu',
  ForgotPassword: 'Quên mật khẩu?',
  InvalidLogin: 'Email hoặc mật khẩu không đúng',
  TermsOfServiceAgreement:
    'Khi đăng nhập, bạn đã đồng ý với điều khoản sử dụng của chúng tôi',
  SeeMore: 'Xem thêm',
  HomeTab: 'Trang chủ',
  SearchTab: 'Tìm kiếm',
  TransactionTab: 'Giao dịch',
  UserTab: 'Tài khoản',
  AccountInfo: 'Thông tin tài khoản',
  NotificationSettings: 'Cài đặt thông báo',
  ShareApplication: 'Chia sẻ ứng dụng',
  InfoAppSetting: 'Thông tin sản phẩm',
  AppContact: 'Liên hệ',
  LogOut: 'Đăng xuất',
  HomeTabTitle: 'Trang chủ',
  TakePicture: 'Chụp ảnh',
  Cancel: 'Huỷ',
  ChoosePictureLocal: 'Chọn ảnh từ thư viện',
  ProductDetail: 'Chi tiết sản phẩm',
  ProductName: 'Tên sản phẩm',
  AllReviews: 'Tất cả đánh giá',
  Colorway: 'Màu chủ đạo',
  Brand: 'Hãng',
  Category: 'Phân khúc',
  NoReview: 'Hiện tại chưa có đánh giá nào.',
  Rating: 'Đánh giá sản phẩm',
  ReleaseDate: 'Ngày ra mắt',
  NewReview: 'Đánh giá mới',
  RatingTitle: 'Đánh giá:',
  RatingPlaceHolder: 'Giày đi êm chân, dáng đẹp,...',
  Detail: 'Chi tiết:',
  PostRating: 'Đăng đánh giá',
  MissingInfoForReview: 'Bạn cần thêm thông tin cá nhân trước khi đánh giá sản phẩm',
  AddInfoForReview: 'Thêm thông tin',
  PleaseWait: 'Xin chờ',
  NewSell: 'Đăng bán sản phẩm',
  Continue: 'Tiếp tục',
  SellShoe: 'Đăng bán',
  RelatedProducts: 'Sản phẩm liên quan',
  ChooseSize: 'Chọn cỡ và giá',
  ErrorPleaseTryAgain: 'Đã có lỗi xảy ra, xin vui lòng thử lại',
  AccountNotVerifieid: 'Tài khoản của bạn chưa được xác thực',
  MissingAddress: 'thiếu địa chỉ giao hàng',
  BuyNow: 'Mua ngay',
  SetBuyPrice: 'Đặt giá mua',
  Checkout: 'Thanh toán',
  BuyProduct: 'Mua sản phẩm',
  ShoeSize: 'Cỡ giày',
  Address: 'Địa chỉ',
  Receipient: 'Nguời nhận',
  ProductPrice: 'Giá sản phẩm',
  ShippingFee: 'Giá chuyển phát nhanh',
  TotalFee: 'Tổng chi phí',
  IntlPayment: 'Thanh toán quốc tế',
  DomesticPayment: 'Thanh toán nội địa',
  PaymentSuccess: 'Đã mua thành công sản phẩm',
  BuyHistory: 'Lịch sử mua',
  SellHistory: 'Lịch sử bán',
  Selling: 'Đang bán',
  Pending: 'Chờ duyệt',
  Sold: 'Đã bán',
  Denied: 'Từ chối',
  Price: 'Giá',
  Condition: 'Tình trạng',
  TransactionDetail: 'Chi tiết đơn hàng',
  Description: 'Miêu tả đơn hàng',
  NewCondition: 'Mới',
  OldCondition: 'Cũ',
  Tainted: 'Ố vàng',
  OutsoleWorn: 'Đế mòn',
  Status: 'Tình trạng',
  TransactionCanceled: 'Đơn hàng bị huỷ',
  TransactionPending: 'Đang xác nhận',
  TransactionProcessed: 'Đã thanh toán',
  ProductNotFound: 'Không tìm thấy sản phẩm bạn muốn?',
  RequestNewProduct: 'Yêu cầu sản phẩm',
  AddReview: 'Thêm đánh giá',
  SortByDate: 'Sắp xếp theo thời gian',
  NoRating: 'Chưa có đánh giá',
};
