export const strings = {
  SignIn: 'Đăng nhập',
  SignUp: 'Đăng kí tài khoản',
  ContinueFacebook: 'Tiếp tục bằng Facebook',
  ContinueGoogle: 'Tiếp tục bằng Google',
  SignUpEmail: 'Đăng kí bằng email',
  MemberAlready: 'Đã đăng kí bằng email?',
  Email: 'Email của bạn',
  Password: 'Mật khẩu',
  ForgotPassword: 'Quên mật khẩu?',
  InvalidLogin: 'Email hoặc mật khẩu không đúng',
  TermsOfServiceAgreement: 'Khi đăng nhập, bạn đã đồng ý với điều khoản sử dụng của chúng tôi',
  SeeMore: 'Xem thêm',
  HomeTab: 'Trang chủ',
  SearchTab: 'Tìm kiếm',
  TransactionTab: 'Giao dịch',
  UserTab: 'Tài khoản',
  AccountInfo: 'Thông tin tài khoản',
  NotificationSettings: 'Cài đặt thông báo',
  ShareApplication: 'Chia sẻ ứng dụng',
  InfoAppSetting: 'Thông tin sản phẩm',
  AppContact: 'Liên hệ',
  LogOut: 'Đăng xuất',
  HomeTabTitle: 'Trang chủ',
  TakePicture: 'Chụp ảnh',
  Cancel: 'Huỷ',
  ChoosePictureLocal: 'Chọn ảnh từ thư viện',
  ProductDetail: 'Chi tiết sản phẩm',
  ProductName: 'Tên sản phẩm',
  Colorway: 'Màu chủ đạo',
  Brand: 'Hãng',
  Category: 'Phân khúc',
  NoReview: 'Hiện tại chưa có đánh giá nào.',
  Rating: 'Đánh giá sản phẩm',
  ReleaseDate: 'Ngày ra mắt',
  NewReview: 'Đánh giá mới',
  RatingTitle: 'Đánh giá:',
  RatingPlaceHolder: 'Giày đi êm chân, dáng đẹp,...',
  Detail: 'Chi tiết:',
  PostRating: 'Đăng đánh giá',
  MissingInfoForReview: 'Bạn cần thêm thông tin cá nhân trước khi đánh giá sản phẩm',
  AddInfoForReview: 'Thêm thông tin',
  PleaseWait: 'Xin chờ'
}
